tools: Do not override method_missing
AutoHCK::Tools::ThreadSafe overrided method_missing to construct a
synchronizing proxy. However, it turned out the mechanism is somewhat
fragile.

For example. debug.rb fails to generate the backtrace because
evaling __callee__ in method_missing does not work. It results in the
following logs and a crash. Another problem is that Sentry tries to call
to_s method on AutoHCK::Tools::ThreadSafe, resulting in a supurious
locking of the mutex. The following backtrace dipicts the situation
where Sentry triggered a lock, and debug.rb interrupting the lock
raised an exception:
["DEBUGGER Exception: /usr/share/gems/gems/debug-1.4.0/lib/debug/thread_client.rb:986",
 #<NameError: undefined local variable or method `__callee__' for #<AutoHCK::Tools::ThreadSafe:0x00007f9d0bf876e0>>,
 ["/var/home/person/HCK-CI/repos/AutoHCK.git/lib/engines/hcktest/tools.rb:68:in `method_missing'",
  "(eval):1:in `method_missing'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/frame_info.rb:109:in `eval'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/frame_info.rb:109:in `callee'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/frame_info.rb:72:in `frame_type'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/thread_client.rb:43:in `default_frame_formatter'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/thread_client.rb:605:in `call'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/thread_client.rb:605:in `frame_str'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/thread_client.rb:592:in `block in show_frames'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/thread_client.rb:589:in `times'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/thread_client.rb:589:in `show_frames'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/thread_client.rb:864:in `wait_next_action_'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/thread_client.rb:676:in `wait_next_action'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/thread_client.rb:284:in `suspend'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/thread_client.rb:217:in `on_breakpoint'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/breakpoint.rb:65:in `suspend'",
  "/usr/share/gems/gems/debug-1.4.0/lib/debug/breakpoint.rb:157:in `block in setup'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/lib/trap.rb:21:in `block in perform_trap'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/lib/engines/hcktest/tools.rb:66:in `synchronize'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/lib/engines/hcktest/tools.rb:66:in `method_missing'",
  "/usr/share/ruby/error_highlight/core_ext.rb:12:in `to_str'",
  "/usr/share/ruby/error_highlight/core_ext.rb:12:in `to_s'",
  "/usr/share/ruby/error_highlight/core_ext.rb:12:in `to_s'",
  "/usr/share/ruby/did_you_mean/core_ext/name_error.rb:15:in `to_s'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-core-4.7.1/lib/sentry/interfaces/single_exception.rb:7:in `message'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-core-4.7.1/lib/sentry/interfaces/single_exception.rb:7:in `initialize'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-core-4.7.1/lib/sentry/interfaces/single_exception.rb:23:in `new'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-core-4.7.1/lib/sentry/interfaces/single_exception.rb:23:in `build_with_stacktrace'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-core-4.7.1/lib/sentry/interfaces/exception.rb:20:in `block in build'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-core-4.7.1/lib/sentry/interfaces/exception.rb:17:in `map'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-core-4.7.1/lib/sentry/interfaces/exception.rb:17:in `build'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-core-4.7.1/lib/sentry/event.rb:137:in `add_exception_interface'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-core-4.7.1/lib/sentry/client.rb:55:in `block in event_from_exception'",
  "<internal:kernel>:90:in `tap'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-core-4.7.1/lib/sentry/client.rb:54:in `event_from_exception'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-core-4.7.1/lib/sentry/hub.rb:99:in `capture_exception'",
  "/var/home/person/HCK-CI/repos/AutoHCK.git/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-core-4.7.1/lib/sentry-ruby.rb:181:in `capture_exception'",
  "./bin/auto_hck:46:in `rescue in <main>'",
  "./bin/auto_hck:8:in `<main>'"]]

Avoiding method_missing results in a suboptimal interface and increases
the amount of boilerplate code. The overhead is minimized with careful
use of blocks and the new act_with_tools method, replacing
handle_results method.

Signed-off-by: Akihiko Odaki <akihiko.odaki@daynix.com>